// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://euhcushllkgxxxmrryof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1aGN1c2hsbGtneHh4bXJyeW9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjA5OTgsImV4cCI6MjA3MDkzNjk5OH0.hB23gvDZfe1OEo03BNUF3uzLRpVGOozcCeD636Ri3sU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});